name: XXX FURRY
description: Bebam leite, é gostoso e faz bem
meta_description: "Um blog de comics de temática furry adulta."

markdown: kramdown
highlighter: pygments
logo: false
paginate: 5
baseurl: /
domain_name: 'xxxfurryyiff.github.io'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'bhttps://xxxfurryyiff.github.io/'
author:         'TOI 5'
