name: XXX FURRY
description: Um blog de conteúdo furry gay adulto. Comics, textos, galerias, yiff e muito mais. Tudo em portugês.
meta_description: "Um blog de conteúdo furry gay adulto. Comics, textos, galerias, yiff e muito mais. Tudo em portugês."

markdown: kramdown
highlighter: pygments
logo: false
paginate: 4
baseurl: https://xxxfurryyiff.github.io/
domain_name: 'xxxfurryyiff.github.io'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]
disqus_shortname: 'xxx-furry'

# Details for the RSS feed generator
url:            'https://xxxfurryyiff.github.io/'
author:         'TOI 5'
